name: CustomGamemodes
version: '1.0-SNAPSHOT'
main: de.tjorven.customGamemodes.CustomGamemodes
api-version: '1.21.8'
commands:
  worlds:
    description: World management commands
    usage: /worlds <subcommand>
